"""
frontend/chatbot.py
----------------------
Floating "AI Mentor" chat assistant, rendered in the bottom-right corner on
every page - ChatGPT-style layout with assistant/user avatars, a typing
spinner, quick-prompt suggestion chips, a welcome message, an auto-scrolling
message list, and mobile-responsive spacing.

Replies are generated by backend.openrouter_client.generate_chat_response(),
which powers the LearnMate AI Career Mentor persona (career guidance,
roadmaps, resumes, interview prep, skill gaps, certifications, etc.).

Streamlit-only: no components.html(), no iframes, no custom JavaScript. The
only "extra" is a small scoped <style> block (plain CSS, injected the same
native way frontend/styles.py already does) that polishes spacing inside
this widget's own container - frontend/styles.py itself is not touched.
"""

from __future__ import annotations

from typing import Callable, Optional

import streamlit as st

from backend.openrouter_client import generate_chat_response as _default_generate_response

# ChatGPT-style quick-start suggestions shown above st.chat_input(). Clicking
# one sends it to the mentor immediately, just like a real ChatGPT suggestion
# chip. Shown only before the conversation starts, exactly like ChatGPT.
SUGGESTIONS = [
    "🎯 Create my personalized career roadmap",
    "📄 Review my resume",
    "💼 Help me prepare for interviews",
    "📚 Recommend free learning resources",
    "🚀 Analyze my skill gaps",
    "🤖 Suggest AI certifications",
]

# Avatars for st.chat_message() - keeps the two roles visually distinct at a
# glance, the same way ChatGPT uses a bot icon vs. a user icon.
ASSISTANT_AVATAR = "🧭"
USER_AVATAR = "🙂"

# How tall the scrollable message list is. Streamlit auto-scrolls a
# fixed-height st.container() to its newest content, which is what gives us
# "auto scroll" without any JavaScript.
MESSAGE_LIST_HEIGHT = 380

# Scoped CSS - only touches elements inside this widget's own
# `.st-key-lm_chatbot` container (the same class frontend/styles.py already
# uses to pin the widget bottom-right), so it can't leak into the rest of
# the app or fight with styles.py's positioning rules.
_CHAT_CSS = """
<style>
/* Tighter, card-like chat bubbles */
.st-key-lm_chatbot [data-testid="stChatMessage"] {
    padding: 8px 12px;
    border-radius: 14px;
    margin-bottom: 6px;
}

/* Quick-prompt chips: rounded, left-aligned, comfortable tap target */
.st-key-lm_chatbot .stButton > button {
    border-radius: 18px;
    padding: 6px 14px;
    font-size: 0.85rem;
    text-align: left;
    white-space: normal;
    line-height: 1.3;
}

/* Primary open/close launcher button reads a bit bolder than the chips */
.st-key-lm_chatbot .stButton:first-of-type > button {
    font-weight: 600;
    border-radius: 24px;
}

/* Clean vertical rhythm between header, caption, and message list */
.st-key-lm_chatbot h4 {
    margin-bottom: 0.1rem;
}
.st-key-lm_chatbot [data-testid="stCaptionContainer"] {
    margin-bottom: 0.5rem;
}

/* Mobile: shrink padding/font so the panel stays comfortable on small screens */
@media (max-width: 480px) {
    .st-key-lm_chatbot [data-testid="stChatMessage"] {
        padding: 6px 10px;
        font-size: 0.9rem;
    }
    .st-key-lm_chatbot .stButton > button {
        font-size: 0.8rem;
        padding: 5px 10px;
    }
}
</style>
"""


def _send_message(text: str, generate_response: Callable[[str, list], str]) -> None:
    """Append the user's message, call the AI mentor, and store the reply.

    `chat_history` is kept in st.session_state as a list of
    {"role": "user"/"assistant", "content": str} dicts - the same shape
    backend.openrouter_client.generate_chat_response() expects, so it can
    be replayed straight back to the API for conversational context.
    """
    text = text.strip()
    if not text:
        return

    history = st.session_state["chat_history"]
    history.append({"role": "user", "content": text})

    with st.spinner("🧭 Your AI Career Mentor is typing..."):
        # Pass everything before this turn as context; the model gets the
        # new message via the `message` argument itself.
        reply = generate_response(text, history[:-1])

    history.append({"role": "assistant", "content": reply})
    st.rerun()


def _render_message_list(history: list[dict[str, str]]) -> None:
    """Render chat history in a fixed-height, auto-scrolling message list."""
    with st.container(height=MESSAGE_LIST_HEIGHT):
        if not history:
            st.markdown(
                "👋 **Hi, I'm your AI Career Mentor!**\n\n"
                "Ask me anything about your career, learning roadmap, resume, "
                "or interview prep - or tap a quick prompt below to get started."
            )
        for turn in history:
            avatar = ASSISTANT_AVATAR if turn["role"] == "assistant" else USER_AVATAR
            with st.chat_message(turn["role"], avatar=avatar):
                st.markdown(turn["content"])


def _render_suggestions(generate_response: Callable[[str, list], str]) -> None:
    """Render ChatGPT-style suggestion chips in a clean two-column grid."""
    st.markdown("**Quick prompts:**")
    cols = st.columns(2)
    for i, suggestion in enumerate(SUGGESTIONS):
        with cols[i % 2]:
            if st.button(suggestion, key=f"suggest_q_{i}", use_container_width=True):
                _send_message(suggestion, generate_response)


def _render_chat_panel(generate_response: Callable[[str, list], str]) -> None:
    """Render the welcome message, chat history, suggestions, and input."""
    history = st.session_state["chat_history"]

    _render_message_list(history)

    # Suggestions only appear before the conversation starts - same
    # ChatGPT-style behavior of clearing them out once you're chatting,
    # which keeps the panel clean and professional.
    if not history:
        _render_suggestions(generate_response)

    prompt = st.chat_input("Ask your AI Career Mentor...", key="chat_input")
    if prompt:
        _send_message(prompt, generate_response)


def render_chatbot_widget(
    generate_response: Optional[Callable[[str, list], str]] = None,
    chat_history: Optional[list] = None,
) -> None:
    """Render the floating AI Mentor widget.

    Args:
        generate_response: Callable(message, chat_history) -> str used to
            generate mentor replies. Defaults to
            backend.openrouter_client.generate_chat_response so the widget
            still works if called with no arguments.
        chat_history: Optional list of {"role", "content"} dicts to seed
            st.session_state["chat_history"] with (kept for API
            compatibility with callers that manage history externally).
    """
    generate_response = generate_response or _default_generate_response

    st.session_state.setdefault("chatbot_open", False)
    if chat_history is not None:
        st.session_state["chat_history"] = chat_history
    else:
        st.session_state.setdefault("chat_history", [])

    st.markdown(_CHAT_CSS, unsafe_allow_html=True)

    # Floating launcher + panel, pinned bottom-right via the "lm_chatbot"
    # container key (Streamlit auto-assigns a `.st-key-lm_chatbot` class,
    # which frontend/styles.py targets with position:fixed). z-index and a
    # bottom-margin keep it from ever overlapping the main UI.
    with st.container(key="lm_chatbot"):
        toggle_label = "✖️ Close AI Mentor" if st.session_state["chatbot_open"] else "💬 AI Mentor"
        if st.button(toggle_label, key="chat_toggle_btn"):
            st.session_state["chatbot_open"] = not st.session_state["chatbot_open"]
            st.rerun()

        if st.session_state["chatbot_open"]:
            st.markdown("#### 🧭 AI Career Mentor")
            st.caption("🟢 Powered by LearnMate AI")
            _render_chat_panel(generate_response)
